# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
jobs:
  build:
    docker:
      - image: cimg/node:14.21.3
    steps:
      - checkout
      - run: npm i
  deploy:
    docker:
      - image: cimg/node:14.21.3
    steps:
      - run: docker login -u "nguyentruonggiang210" -p "$DOCKERHUB_PASSWORD"
      - run: docker build -t simple-node .
      - run: docker tag simple-node nguyentruonggiang210/simple-node:latest
      
workflows: 
  build_deploy:
    jobs:
      - build
      - deploy

        
