name: Continous Integration and Deployment # name of process

on: # when process run
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI Trigger on Push 
        id: CCI_01
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: 1c74215a52a1df9a70a039774eb97f8a9026e8f0
    